databases:
  - name: dpg-chvpqej3cv26tflsh7g0-a
    databaseName: pizzaapi8
    user: pizzaapi8_user

services:
  - type: web
    name: dpg-chvpqej3cv26tflsh7g0-a
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-chvpqej3cv26tflsh7g0-a
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false