databases:
  - name: dpg-ci09o8m4dad75tuqci8g-a
    databaseName: moyrest
    user: moyrest_user

services:
  - type: web
    name: moyrest
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moyrest
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false